### ISSUE TITLE
Mod crashing multiplayer server

### ISSUE THREAD

**Issue by pinchese** [RandomMcSomethin/moisturization#3]
Hello! I'm self-hosting a server for me and my friends on minecraft 1.18.2, and when one of them enabled the sprinkler with a lever, it crashed. I tested the mod in singleplayer, and it worked perfectly fine, and every time I start the server it crashes because of this mod.

Here's the output log!

```
1:33 PM
... 5 more
run.sh
1:33 PM
at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:907) ~[server-intermediary.jar:?]
run.sh
1:33 PM
at net.minecraft.server.world.ServerWorld.tick(ServerWorld:368) ~[?:?]
run.sh
1:33 PM
at net.minecraft.world.World.tickBlockEntities(World:475) ~[?:?]
run.sh
1:33 PM
at net.minecraft.world.chunk.WorldChunk$WrappedBlockEntityTickInvoker.tick(WorldChunk:713) ~[?:?]
run.sh
1:33 PM
at net.minecraft.world.chunk.WorldChunk$DirectBlockEntityTickInvoker.tick(WorldChunk:659) ~[?:?]
run.sh
1:33 PM
at com.random.moisturization.blocks.SprinklerBlockEntity.tick(SprinklerBlockEntity.java:64) ~[moisturization-1.1.2.jar:?]
run.sh
1:33 PM
at com.random.moisturization.blocks.SprinklerBlock.spawnParticles(SprinklerBlock.java:105) ~[moisturization-1.1.2.jar:?]
run.sh
1:33 PM
at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
run.sh
1:33 PM
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
run.sh
1:33 PM
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
run.sh
1:33 PM
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
run.sh
1:33 PM
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:407) ~[fabric-loader-0.14.8.jar:?]
run.sh
1:33 PM
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:454) ~[fabric-loader-0.14.8.jar:?]
run.sh
1:33 PM
at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.8.jar:?]
run.sh
1:33 PM
Caused by: java.lang.RuntimeException: Cannot load class com.random.moisturization.client.MoisturizationClient in environment type SERVER
run.sh
1:33 PM
at java.lang.Thread.run(Thread.java:833) [?:?]
run.sh
1:33 PM
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[server-intermediary.jar:?]
run.sh
1:33 PM
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697) ~[server-intermediary.jar:?]
run.sh
1:33 PM
at net.minecraft.server.MinecraftServer.tick(MinecraftServer:851) ~[server-intermediary.jar:?]
run.sh
1:33 PM
at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:322) ~[?:?]
run.sh
1:33 PM
at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:911) ~[server-intermediary.jar:?]
run.sh
1:33 PM
at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
run.sh
1:33 PM
net.minecraft.class_148: Ticking block entity
run.sh
1:33 PM
[13:33:25] [Server thread/ERROR]: Encountered an unexpected exception
```

*read bottom to top*

This mod seems really cool, so if you get it working again, I'd love to know!

**Comment by RandomMcSomethin** [comment]
I'll give it a check tomorrow and see what the problem is.  Thanks for letting me know!
